apiVersion: argoproj.i/v1alpha1
kind: Rollout
metadata:
  name: helm-practice-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector: 
    matchLabels:
      app: helm-practice
  template:
    metadata:
      labels:
        app: helm-practice
    spec:
      containers:
        - name: helm-practice-containers
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80