replicaCount: 4

strategy:
  canary:
    steps: []

image:
  repository: ghcr.io/craztool/helm-practice
  tag: 0dc6420d4d414d14b3b519c8ed9705584164f756

service:
  port: 80

ingress:
  host: helm.local