replicaCount: 4

strategy:
  canary:
    steps:
    - setWeight: 100
    - pause: {}

image:
  repository: ghcr.io/craztool/helm-practice
  tag: 98ca8b3b98b6e9b9ff3231fa98719c7e01cefdbc

service:
  port: 80

ingress:
  host: helm.local