replicaCount: 4

strategy:
  canary:
    steps: []

image:
  repository: ghcr.io/craztool/helm-practice
  tag: b0c94fe63f591fa0b7382758052a9310448a8d1e

service:
  port: 80

ingress:
  host: helm.local